[programs.localnet]
staking = "BtDDM9Nve5JXUVvDg8wmLDVwzgGB8pJ6oum4fGRKM8Av"

[programs.devnet]
staking = "BtDDM9Nve5JXUVvDg8wmLDVwzgGB8pJ6oum4fGRKM8Av"

[programs.mainnet]
staking = "BtDDM9Nve5JXUVvDg8wmLDVwzgGB8pJ6oum4fGRKM8Av"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
#url = "https://api.devnet.solana.com"
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg" # metaplex: auth program

[[test.validator.clone]]
address = "ocp4vWUzA2z2XMYJ3QhM9vWdyoyoQwAFJhRdVTbvo9E"

[[test.validator.clone]]
address = "CMTQqjzH6Anr9XcPVt73EFDTjWkJWPzH7H6DtvhHcyzV"

#[[test.validator.clone]]
#address = "6Huqrb4xxmmNA4NufYdgpmspoLmjXFd3qEfteCddLgSz" # ocp: policy (DEVNET allow all)

[[test.validator.clone]]
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9" # mpl: default allowlist

[[test.validator.clone]]
address = "EkHNhudhddaY5nj7exQzJmCzU2xQQLFCGAXHXZqZHBPg" # mpl: custom allowlist with FloppyLabs staking program
