[programs.localnet]
staking = "BtDDM9Nve5JXUVvDg8wmLDVwzgGB8pJ6oum4fGRKM8Av"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
